In [1]:
# 为环境变量做好准备
import os
from io import StringIO
from dotenv import load_dotenv

env_text = """
HOME=./eztransfer_modelzoo
"""

load_dotenv(stream=StringIO(env_text), override=True, verbose=True)
os.environ.get("HOME")

'./eztransfer_modelzoo'

In [2]:
# 让本地的 easytransfer 的优先级更高
import sys
sys.path.insert(0, os.path.abspath('../'))
sys.path

['d:\\code\\github\\EasyTransfer',
 'd:\\code\\github\\EasyTransfer\\examples',
 'c:\\Users\\tzh\\.vscode\\extensions\\ms-toolsai.jupyter-2021.11.1001550889\\pythonFiles\\vscode_datascience_helpers',
 'c:\\Users\\tzh\\.vscode\\extensions\\ms-toolsai.jupyter-2021.11.1001550889\\pythonFiles',
 'c:\\Users\\tzh\\.vscode\\extensions\\ms-toolsai.jupyter-2021.11.1001550889\\pythonFiles\\lib\\python',
 'C:\\Anaconda3\\envs\\tf2\\python39.zip',
 'C:\\Anaconda3\\envs\\tf2\\DLLs',
 'C:\\Anaconda3\\envs\\tf2\\lib',
 'C:\\Anaconda3\\envs\\tf2',
 '',
 'C:\\Anaconda3\\envs\\tf2\\lib\\site-packages',
 'C:\\Anaconda3\\envs\\tf2\\lib\\site-packages\\win32',
 'C:\\Anaconda3\\envs\\tf2\\lib\\site-packages\\win32\\lib',
 'C:\\Anaconda3\\envs\\tf2\\lib\\site-packages\\Pythonwin']

In [3]:
# 导入 easytransfer, 并验证, 因为原始的没有 __version__ 这个参数
import importlib
import easytransfer as easytransfer
importlib.reload(easytransfer)
print(easytransfer.__version__)

import tensorflow as tf

INFO:tensorflow:*********** tf.__version__ is 2.7.0 ******
1.0.0


In [4]:
# jupyter 特殊操作
old_argv = sys.argv
print(old_argv)
sys.argv = old_argv[:1]

['ipykernel_launcher', '--ip=127.0.0.1', '--stdin=9013', '--control=9011', '--hb=9010', '--Session.signature_scheme="hmac-sha256"', '--Session.key=b"7be78974-015d-45d2-ac46-d2f576d673d1"', '--shell=9012', '--transport="tcp"', '--iopub=9014', '--f=C:\\Users\\tzh\\AppData\\Local\\Temp\\tmp-35480UqUToz61CRgM.json']


In [5]:
from easytransfer.model_zoo.modeling_bert import BertConfig, BertPreTrainedModel, MyBertPreTrainedModel

In [6]:
bert_config_path = "D:/code/py_nlp_classify/model/bert/google-bert-base-zh/config.json"
bert_config = BertConfig.get(bert_config_path)
bert_config

In [7]:
bert_model = BertPreTrainedModel(bert_config)
bert_model

In [8]:
my_bert_model = MyBertPreTrainedModel(bert_config)
my_bert_model

In [10]:
out_put = my_bert_model(my_bert_model.dummy_inputs(512), mode="eval", output_features=False)
print(type(out_put))
print(len(out_put))

for item in out_put:
    print(type(item))
    print(item.shape)

out_put

input_shape [1, 512]
<class 'tuple'>
3
<class 'tensorflow.python.framework.ops.EagerTensor'>
(512, 21128)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(1, 2)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(1, 768)


(<tf.Tensor: shape=(512, 21128), dtype=float32, numpy=
 array([[-0.4718424 ,  0.15066633,  0.11407417, ..., -0.3093407 ,
         -0.6125126 , -0.71065575],
        [-0.4718424 ,  0.15066633,  0.11407417, ..., -0.3093407 ,
         -0.6125126 , -0.71065575],
        [-0.4718424 ,  0.15066633,  0.11407417, ..., -0.3093407 ,
         -0.6125126 , -0.71065575],
        ...,
        [-0.4718424 ,  0.15066633,  0.11407417, ..., -0.3093407 ,
         -0.6125126 , -0.71065575],
        [-0.4718424 ,  0.15066633,  0.11407417, ..., -0.3093407 ,
         -0.6125126 , -0.71065575],
        [-0.4718424 ,  0.15066633,  0.11407417, ..., -0.3093407 ,
         -0.6125126 , -0.71065575]], dtype=float32)>,
 <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.10771573, 0.11877879]], dtype=float32)>,
 <tf.Tensor: shape=(1, 768), dtype=float32, numpy=
 array([[-2.61349618e-01,  1.67544410e-01, -4.50660944e-01,
         -4.07234311e-01,  2.75090694e-01, -6.27516150e-01,
          2.78590143e-01, -5.126

In [ ]:
bert_model(bert_model.dummy_inputs(512), mode="eval", output_features=False)

In [ ]:
archive_file = "D:/code/py_nlp_classify/model/bert/google-bert-base-zh/bert_model.ckpt"

In [ ]:
bert_model._init_from_pretrained_model(archive_file)

In [ ]:
bert_model(bert_model.dummy_inputs(512), mode="eval", output_features=False)

In [ ]:
# import importlib
# from easytransfer.model_zoo import modeling_utils, modeling_bert
# importlib.reload(modeling_utils)
# importlib.reload(modeling_bert)
# from easytransfer.model_zoo.modeling_bert import BertConfig, BertPreTrainedModel, MyBertPreTrainedModel
# from easytransfer.model_zoo.modeling_utils import PretrainedConfig

# bert_config = BertConfig.get(bert_config_path)
# my_bert_model = MyBertPreTrainedModel(bert_config)

In [ ]:
my_bert_model._init_from_pretrained_model(archive_file)

In [ ]:
my_bert_model(my_bert_model.dummy_inputs(512), mode="eval", output_features=False)

In [ ]:
all_equal = []
for x, y in zip(bert_model.weights, my_bert_model.weights):
    all_equal.append(tf.equal(x, y).numpy().all())

print(all(all_equal))

In [ ]:
[v.name for v in bert_model.weights]

In [ ]:
[v.name for v in my_bert_model.weights]

In [ ]:
[v.name for v in my_bert_model.bert.encoder.weights]

In [ ]:
[v.name for v in my_bert_model.bert.embeddings.weights]

In [ ]:
[v.name for v in my_bert_model.mlm.weights]

In [ ]:
[v.name for v in my_bert_model.nsp.weights]

In [ ]:
tf.train.list_variables('D:/code/py_nlp_classify/model/bert/google-bert-base-zh/bert_model.ckpt')

In [ ]:
reader = tf.train.load_checkpoint("D:/code/py_nlp_classify/model/bert/google-bert-base-zh/bert_model.ckpt")
var_to_shape_map = reader.get_variable_to_shape_map()

In [ ]:
list(sorted(var_to_shape_map.keys()))