In [1]:
# 为环境变量做好准备
import os
from io import StringIO
from dotenv import load_dotenv

env_text = """
HOME=./eztransfer_modelzoo
"""

load_dotenv(stream=StringIO(env_text), override=True, verbose=True)
os.environ.get("HOME")

'./eztransfer_modelzoo'

In [2]:
# 让本地的 easytransfer 的优先级更高
import sys
sys.path.insert(0, os.path.abspath('../'))
sys.path

['d:\\code\\github\\EasyTransfer',
 'd:\\code\\github\\EasyTransfer\\examples',
 'c:\\Users\\tzh\\.vscode\\extensions\\ms-toolsai.jupyter-2021.11.1001550889\\pythonFiles\\vscode_datascience_helpers',
 'c:\\Users\\tzh\\.vscode\\extensions\\ms-toolsai.jupyter-2021.11.1001550889\\pythonFiles',
 'c:\\Users\\tzh\\.vscode\\extensions\\ms-toolsai.jupyter-2021.11.1001550889\\pythonFiles\\lib\\python',
 'C:\\Anaconda3\\envs\\tf2\\python39.zip',
 'C:\\Anaconda3\\envs\\tf2\\DLLs',
 'C:\\Anaconda3\\envs\\tf2\\lib',
 'C:\\Anaconda3\\envs\\tf2',
 '',
 'C:\\Anaconda3\\envs\\tf2\\lib\\site-packages',
 'C:\\Anaconda3\\envs\\tf2\\lib\\site-packages\\win32',
 'C:\\Anaconda3\\envs\\tf2\\lib\\site-packages\\win32\\lib',
 'C:\\Anaconda3\\envs\\tf2\\lib\\site-packages\\Pythonwin']

In [3]:
# 导入 easytransfer, 并验证, 因为原始的没有 __version__ 这个参数
import importlib
import easytransfer as easytransfer
importlib.reload(easytransfer)
easytransfer.__version__

import tensorflow as tf

INFO:tensorflow:*********** tf.__version__ is 2.7.0 ******


In [4]:
# jupyter 特殊操作
old_argv = sys.argv
print(old_argv)
sys.argv = old_argv[:1]

['ipykernel_launcher', '--ip=127.0.0.1', '--stdin=9003', '--control=9001', '--hb=9000', '--Session.signature_scheme="hmac-sha256"', '--Session.key=b"db2664f3-b814-4765-864b-23da990ca90f"', '--shell=9002', '--transport="tcp"', '--iopub=9004', '--f=C:\\Users\\tzh\\AppData\\Local\\Temp\\tmp-31956oKbWjIUCEo2T.json']


In [5]:
from easytransfer.model_zoo.modeling_bert import BertConfig, BertPreTrainedModel, MyBertPreTrainedModel

In [6]:
bert_config_path = "D:/code/py_nlp_classify/model/bert/google-bert-base-zh/config.json"
bert_config = BertConfig.get(bert_config_path)
bert_config

In [7]:
bert_model = BertPreTrainedModel(bert_config)
bert_model

In [8]:
my_bert_model = MyBertPreTrainedModel(bert_config)
my_bert_model

In [9]:
out_put = my_bert_model(my_bert_model.dummy_inputs(512), mode="eval", output_features=False)
print(type(out_put))
print(len(out_put))

for item in out_put:
    print(type(item))
    print(item.shape)

out_put

input_shape [1, 512]
<class 'tuple'>
3
<class 'tensorflow.python.framework.ops.EagerTensor'>
(512, 21128)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(1, 2)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(1, 768)


(<tf.Tensor: shape=(512, 21128), dtype=float32, numpy=
 array([[-0.4718424 ,  0.15066633,  0.11407417, ..., -0.3093407 ,
         -0.6125126 , -0.71065575],
        [-0.4718424 ,  0.15066633,  0.11407417, ..., -0.3093407 ,
         -0.6125126 , -0.71065575],
        [-0.4718424 ,  0.15066633,  0.11407417, ..., -0.3093407 ,
         -0.6125126 , -0.71065575],
        ...,
        [-0.4718424 ,  0.15066633,  0.11407417, ..., -0.3093407 ,
         -0.6125126 , -0.71065575],
        [-0.4718424 ,  0.15066633,  0.11407417, ..., -0.3093407 ,
         -0.6125126 , -0.71065575],
        [-0.4718424 ,  0.15066633,  0.11407417, ..., -0.3093407 ,
         -0.6125126 , -0.71065575]], dtype=float32)>,
 <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.10771573, 0.11877879]], dtype=float32)>,
 <tf.Tensor: shape=(1, 768), dtype=float32, numpy=
 array([[-2.61349618e-01,  1.67544410e-01, -4.50660944e-01,
         -4.07234311e-01,  2.75090694e-01, -6.27516150e-01,
          2.78590143e-01, -5.126

In [10]:
bert_model(bert_model.dummy_inputs(512), mode="eval", output_features=False)

input_shape [1, 512]


(<tf.Tensor: shape=(512, 21128), dtype=float32, numpy=
 array([[ 0.2335467 , -0.6062009 ,  0.37243122, ..., -0.02789687,
          1.1900101 , -0.04584426],
        [ 0.2335467 , -0.6062009 ,  0.37243122, ..., -0.02789687,
          1.1900101 , -0.04584426],
        [ 0.2335467 , -0.6062009 ,  0.37243122, ..., -0.02789687,
          1.1900101 , -0.04584426],
        ...,
        [ 0.2335467 , -0.6062009 ,  0.37243122, ..., -0.02789687,
          1.1900101 , -0.04584426],
        [ 0.2335467 , -0.6062009 ,  0.37243122, ..., -0.02789687,
          1.1900101 , -0.04584426],
        [ 0.2335467 , -0.6062009 ,  0.37243122, ..., -0.02789687,
          1.1900101 , -0.04584426]], dtype=float32)>,
 <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-0.05420166, -0.00963133]], dtype=float32)>,
 <tf.Tensor: shape=(1, 768), dtype=float32, numpy=
 array([[-5.32185376e-01, -5.94466746e-01, -4.74589109e-01,
          5.17674029e-01,  1.22628480e-01, -7.56749511e-01,
          1.34524375e-01,  1.2

In [11]:
archive_file = "D:/code/py_nlp_classify/model/bert/google-bert-base-zh/bert_model.ckpt"

In [12]:
bert_model._init_from_pretrained_model(archive_file)

INFO:tensorflow:从文件中还原预训练模型
INFO:tensorflow:Load weights from D:/code/py_nlp_classify/model/bert/google-bert-base-zh/bert_model.ckpt


In [13]:
bert_model(bert_model.dummy_inputs(512), mode="eval", output_features=False)

input_shape [1, 512]


(<tf.Tensor: shape=(512, 21128), dtype=float32, numpy=
 array([[-7.625208, -7.291108, -7.961869, ..., -4.587221, -8.310778,
         -7.2949  ],
        [-7.625208, -7.291108, -7.961869, ..., -4.587221, -8.310778,
         -7.2949  ],
        [-7.625208, -7.291108, -7.961869, ..., -4.587221, -8.310778,
         -7.2949  ],
        ...,
        [-7.625208, -7.291108, -7.961869, ..., -4.587221, -8.310778,
         -7.2949  ],
        [-7.625208, -7.291108, -7.961869, ..., -4.587221, -8.310778,
         -7.2949  ],
        [-7.625208, -7.291108, -7.961869, ..., -4.587221, -8.310778,
         -7.2949  ]], dtype=float32)>,
 <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[ 3.107627  , -0.80155367]], dtype=float32)>,
 <tf.Tensor: shape=(1, 768), dtype=float32, numpy=
 array([[ 9.68027830e-01,  8.67992640e-01,  9.84189093e-01,
          4.46009457e-01,  1.67544588e-01, -6.17821753e-01,
         -2.94417173e-01,  8.58661354e-01,  3.78999293e-01,
         -9.56552684e-01,  9.87426698e-01,

In [14]:
# import importlib
# from easytransfer.model_zoo import modeling_utils, modeling_bert
# importlib.reload(modeling_utils)
# importlib.reload(modeling_bert)
# from easytransfer.model_zoo.modeling_bert import BertConfig, BertPreTrainedModel, MyBertPreTrainedModel
# from easytransfer.model_zoo.modeling_utils import PretrainedConfig

# bert_config = BertConfig.get(bert_config_path)
# my_bert_model = MyBertPreTrainedModel(bert_config)

In [15]:
my_bert_model._init_from_pretrained_model(archive_file)

从文件中还原预训练模型
INFO:tensorflow:Load weights from D:/code/py_nlp_classify/model/bert/google-bert-base-zh/bert_model.ckpt


In [16]:
my_bert_model(my_bert_model.dummy_inputs(512), mode="eval", output_features=False)

input_shape [1, 512]


(<tf.Tensor: shape=(512, 21128), dtype=float32, numpy=
 array([[-7.625208, -7.291108, -7.961869, ..., -4.587221, -8.310778,
         -7.2949  ],
        [-7.625208, -7.291108, -7.961869, ..., -4.587221, -8.310778,
         -7.2949  ],
        [-7.625208, -7.291108, -7.961869, ..., -4.587221, -8.310778,
         -7.2949  ],
        ...,
        [-7.625208, -7.291108, -7.961869, ..., -4.587221, -8.310778,
         -7.2949  ],
        [-7.625208, -7.291108, -7.961869, ..., -4.587221, -8.310778,
         -7.2949  ],
        [-7.625208, -7.291108, -7.961869, ..., -4.587221, -8.310778,
         -7.2949  ]], dtype=float32)>,
 <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[ 3.107627  , -0.80155367]], dtype=float32)>,
 <tf.Tensor: shape=(1, 768), dtype=float32, numpy=
 array([[ 9.68027830e-01,  8.67992640e-01,  9.84189093e-01,
          4.46009457e-01,  1.67544588e-01, -6.17821753e-01,
         -2.94417173e-01,  8.58661354e-01,  3.78999293e-01,
         -9.56552684e-01,  9.87426698e-01,

In [17]:
all_equal = []
for x, y in zip(bert_model.weights, my_bert_model.weights):
    all_equal.append(tf.equal(x, y).numpy().all())

print(all(all_equal))

True


In [18]:
[v.name for v in bert_model.weights]

['bert_pre_trained_model/bert/embeddings/word_embeddings:0',
 'bert_pre_trained_model/bert/embeddings/position_embeddings:0',
 'bert_pre_trained_model/bert/embeddings/token_type_embeddings:0',
 'bert_pre_trained_model/bert/embeddings/LayerNorm/gamma:0',
 'bert_pre_trained_model/bert/embeddings/LayerNorm/beta:0',
 'bert_pre_trained_model/bert/encoder/layer_0/attention/self/query/kernel:0',
 'bert_pre_trained_model/bert/encoder/layer_0/attention/self/query/bias:0',
 'bert_pre_trained_model/bert/encoder/layer_0/attention/self/key/kernel:0',
 'bert_pre_trained_model/bert/encoder/layer_0/attention/self/key/bias:0',
 'bert_pre_trained_model/bert/encoder/layer_0/attention/self/value/kernel:0',
 'bert_pre_trained_model/bert/encoder/layer_0/attention/self/value/bias:0',
 'bert_pre_trained_model/bert/encoder/layer_0/attention/output/dense/kernel:0',
 'bert_pre_trained_model/bert/encoder/layer_0/attention/output/dense/bias:0',
 'bert_pre_trained_model/bert/encoder/layer_0/attention/output/LayerNo

In [19]:
[v.name for v in my_bert_model.weights]

['my_bert_pre_trained_model/bert/embeddings/word_embeddings:0',
 'my_bert_pre_trained_model/bert/embeddings/position_embeddings:0',
 'my_bert_pre_trained_model/bert/embeddings/token_type_embeddings:0',
 'my_bert_pre_trained_model/bert/embeddings/LayerNorm/gamma:0',
 'my_bert_pre_trained_model/bert/embeddings/LayerNorm/beta:0',
 'my_bert_pre_trained_model/bert/encoder/layer_0/attention/self/query/kernel:0',
 'my_bert_pre_trained_model/bert/encoder/layer_0/attention/self/query/bias:0',
 'my_bert_pre_trained_model/bert/encoder/layer_0/attention/self/key/kernel:0',
 'my_bert_pre_trained_model/bert/encoder/layer_0/attention/self/key/bias:0',
 'my_bert_pre_trained_model/bert/encoder/layer_0/attention/self/value/kernel:0',
 'my_bert_pre_trained_model/bert/encoder/layer_0/attention/self/value/bias:0',
 'my_bert_pre_trained_model/bert/encoder/layer_0/attention/output/dense/kernel:0',
 'my_bert_pre_trained_model/bert/encoder/layer_0/attention/output/dense/bias:0',
 'my_bert_pre_trained_model/ber

In [20]:
[v.name for v in my_bert_model.bert.encoder.weights]

['my_bert_pre_trained_model/bert/encoder/layer_0/attention/self/query/kernel:0',
 'my_bert_pre_trained_model/bert/encoder/layer_0/attention/self/query/bias:0',
 'my_bert_pre_trained_model/bert/encoder/layer_0/attention/self/key/kernel:0',
 'my_bert_pre_trained_model/bert/encoder/layer_0/attention/self/key/bias:0',
 'my_bert_pre_trained_model/bert/encoder/layer_0/attention/self/value/kernel:0',
 'my_bert_pre_trained_model/bert/encoder/layer_0/attention/self/value/bias:0',
 'my_bert_pre_trained_model/bert/encoder/layer_0/attention/output/dense/kernel:0',
 'my_bert_pre_trained_model/bert/encoder/layer_0/attention/output/dense/bias:0',
 'my_bert_pre_trained_model/bert/encoder/layer_0/attention/output/LayerNorm/gamma:0',
 'my_bert_pre_trained_model/bert/encoder/layer_0/attention/output/LayerNorm/beta:0',
 'my_bert_pre_trained_model/bert/encoder/layer_0/intermediate/dense/kernel:0',
 'my_bert_pre_trained_model/bert/encoder/layer_0/intermediate/dense/bias:0',
 'my_bert_pre_trained_model/bert/

In [21]:
[v.name for v in my_bert_model.bert.embeddings.weights]

['my_bert_pre_trained_model/bert/embeddings/word_embeddings:0',
 'my_bert_pre_trained_model/bert/embeddings/position_embeddings:0',
 'my_bert_pre_trained_model/bert/embeddings/token_type_embeddings:0',
 'my_bert_pre_trained_model/bert/embeddings/LayerNorm/gamma:0',
 'my_bert_pre_trained_model/bert/embeddings/LayerNorm/beta:0']

In [22]:
[v.name for v in my_bert_model.mlm.weights]

['my_bert_pre_trained_model/cls/predictions/output_bias:0',
 'my_bert_pre_trained_model/cls/predictions/transform/dense/kernel:0',
 'my_bert_pre_trained_model/cls/predictions/transform/dense/bias:0',
 'my_bert_pre_trained_model/cls/predictions/transform/LayerNorm/gamma:0',
 'my_bert_pre_trained_model/cls/predictions/transform/LayerNorm/beta:0',
 'my_bert_pre_trained_model/bert/embeddings/word_embeddings:0',
 'my_bert_pre_trained_model/bert/embeddings/position_embeddings:0',
 'my_bert_pre_trained_model/bert/embeddings/token_type_embeddings:0',
 'my_bert_pre_trained_model/bert/embeddings/LayerNorm/gamma:0',
 'my_bert_pre_trained_model/bert/embeddings/LayerNorm/beta:0']

In [23]:
[v.name for v in my_bert_model.nsp.weights]

['my_bert_pre_trained_model/cls/seq_relationship/output_weights:0',
 'my_bert_pre_trained_model/cls/seq_relationship/output_bias:0']

In [24]:
tf.train.list_variables('D:/code/py_nlp_classify/model/bert/google-bert-base-zh/bert_model.ckpt')

[('bert/embeddings/LayerNorm/beta', [768]),
 ('bert/embeddings/LayerNorm/gamma', [768]),
 ('bert/embeddings/position_embeddings', [512, 768]),
 ('bert/embeddings/token_type_embeddings', [2, 768]),
 ('bert/embeddings/word_embeddings', [21128, 768]),
 ('bert/encoder/layer_0/attention/output/LayerNorm/beta', [768]),
 ('bert/encoder/layer_0/attention/output/LayerNorm/gamma', [768]),
 ('bert/encoder/layer_0/attention/output/dense/bias', [768]),
 ('bert/encoder/layer_0/attention/output/dense/kernel', [768, 768]),
 ('bert/encoder/layer_0/attention/self/key/bias', [768]),
 ('bert/encoder/layer_0/attention/self/key/kernel', [768, 768]),
 ('bert/encoder/layer_0/attention/self/query/bias', [768]),
 ('bert/encoder/layer_0/attention/self/query/kernel', [768, 768]),
 ('bert/encoder/layer_0/attention/self/value/bias', [768]),
 ('bert/encoder/layer_0/attention/self/value/kernel', [768, 768]),
 ('bert/encoder/layer_0/intermediate/dense/bias', [3072]),
 ('bert/encoder/layer_0/intermediate/dense/kernel',

In [25]:
reader = tf.train.load_checkpoint("D:/code/py_nlp_classify/model/bert/google-bert-base-zh/bert_model.ckpt")
var_to_shape_map = reader.get_variable_to_shape_map()

In [26]:
list(sorted(var_to_shape_map.keys()))

['bert/embeddings/LayerNorm/beta',
 'bert/embeddings/LayerNorm/gamma',
 'bert/embeddings/position_embeddings',
 'bert/embeddings/token_type_embeddings',
 'bert/embeddings/word_embeddings',
 'bert/encoder/layer_0/attention/output/LayerNorm/beta',
 'bert/encoder/layer_0/attention/output/LayerNorm/gamma',
 'bert/encoder/layer_0/attention/output/dense/bias',
 'bert/encoder/layer_0/attention/output/dense/kernel',
 'bert/encoder/layer_0/attention/self/key/bias',
 'bert/encoder/layer_0/attention/self/key/kernel',
 'bert/encoder/layer_0/attention/self/query/bias',
 'bert/encoder/layer_0/attention/self/query/kernel',
 'bert/encoder/layer_0/attention/self/value/bias',
 'bert/encoder/layer_0/attention/self/value/kernel',
 'bert/encoder/layer_0/intermediate/dense/bias',
 'bert/encoder/layer_0/intermediate/dense/kernel',
 'bert/encoder/layer_0/output/LayerNorm/beta',
 'bert/encoder/layer_0/output/LayerNorm/gamma',
 'bert/encoder/layer_0/output/dense/bias',
 'bert/encoder/layer_0/output/dense/kernel