In [1]:
# 为环境变量做好准备
import os
from io import StringIO
from dotenv import load_dotenv

env_text = """
HOME=./eztransfer_modelzoo
"""

load_dotenv(stream=StringIO(env_text), override=True, verbose=True)
os.environ.get("HOME")

'./eztransfer_modelzoo'

In [2]:
# 让本地的 easytransfer 的优先级更高
import sys
sys.path.insert(0, os.path.abspath('../'))
sys.path

['d:\\code\\github\\EasyTransfer',
 'd:\\code\\github\\EasyTransfer\\examples',
 'c:\\Users\\tzh\\.vscode\\extensions\\ms-toolsai.jupyter-2021.11.1001550889\\pythonFiles\\vscode_datascience_helpers',
 'c:\\Users\\tzh\\.vscode\\extensions\\ms-toolsai.jupyter-2021.11.1001550889\\pythonFiles',
 'c:\\Users\\tzh\\.vscode\\extensions\\ms-toolsai.jupyter-2021.11.1001550889\\pythonFiles\\lib\\python',
 'C:\\Anaconda3\\envs\\tf2\\python39.zip',
 'C:\\Anaconda3\\envs\\tf2\\DLLs',
 'C:\\Anaconda3\\envs\\tf2\\lib',
 'C:\\Anaconda3\\envs\\tf2',
 '',
 'C:\\Anaconda3\\envs\\tf2\\lib\\site-packages',
 'C:\\Anaconda3\\envs\\tf2\\lib\\site-packages\\win32',
 'C:\\Anaconda3\\envs\\tf2\\lib\\site-packages\\win32\\lib',
 'C:\\Anaconda3\\envs\\tf2\\lib\\site-packages\\Pythonwin']

In [3]:
# 导入 easytransfer, 并验证, 因为原始的没有 __version__ 这个参数
import importlib
import easytransfer as easytransfer
importlib.reload(easytransfer)
easytransfer.__version__

import tensorflow as tf

INFO:tensorflow:*********** tf.__version__ is 2.7.0 ******


In [4]:
# jupyter 特殊操作
old_argv = sys.argv
print(old_argv)
sys.argv = old_argv[:1]

['ipykernel_launcher', '--ip=127.0.0.1', '--stdin=9018', '--control=9016', '--hb=9015', '--Session.signature_scheme="hmac-sha256"', '--Session.key=b"43401d51-c03b-4494-84da-34e48ffdd397"', '--shell=9017', '--transport="tcp"', '--iopub=9019', '--f=C:\\Users\\tzh\\AppData\\Local\\Temp\\tmp-31956Hwb5mLyK44gt.json']


In [5]:
from easytransfer.model_zoo.modeling_bert import BertConfig, BertPreTrainedModel, MyBertPreTrainedModel

In [6]:
bert_config_path = "D:/code/py_nlp_classify/model/bert/google-bert-base-zh/config.json"
bert_config = BertConfig.get(bert_config_path)
bert_config

In [7]:
bert_model = BertPreTrainedModel(bert_config)
bert_model

In [8]:
my_bert_model = MyBertPreTrainedModel(bert_config)
my_bert_model

In [9]:
out_put = my_bert_model(my_bert_model.dummy_inputs(512), mode="eval", output_features=False)
print(type(out_put))
print(len(out_put))

for item in out_put:
    print(type(item))
    print(item.shape)

out_put

input_shape [1, 512]
<class 'tuple'>
3
<class 'tensorflow.python.framework.ops.EagerTensor'>
(512, 21128)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(1, 2)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(1, 768)


(<tf.Tensor: shape=(512, 21128), dtype=float32, numpy=
 array([[-0.4718424 ,  0.15066633,  0.11407417, ..., -0.3093407 ,
         -0.6125126 , -0.71065575],
        [-0.4718424 ,  0.15066633,  0.11407417, ..., -0.3093407 ,
         -0.6125126 , -0.71065575],
        [-0.4718424 ,  0.15066633,  0.11407417, ..., -0.3093407 ,
         -0.6125126 , -0.71065575],
        ...,
        [-0.4718424 ,  0.15066633,  0.11407417, ..., -0.3093407 ,
         -0.6125126 , -0.71065575],
        [-0.4718424 ,  0.15066633,  0.11407417, ..., -0.3093407 ,
         -0.6125126 , -0.71065575],
        [-0.4718424 ,  0.15066633,  0.11407417, ..., -0.3093407 ,
         -0.6125126 , -0.71065575]], dtype=float32)>,
 <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.10771573, 0.11877879]], dtype=float32)>,
 <tf.Tensor: shape=(1, 768), dtype=float32, numpy=
 array([[-2.61349618e-01,  1.67544410e-01, -4.50660944e-01,
         -4.07234311e-01,  2.75090694e-01, -6.27516150e-01,
          2.78590143e-01, -5.126

In [10]:
bert_model(bert_model.dummy_inputs(512), mode="eval", output_features=False)

input_shape [1, 512]


(<tf.Tensor: shape=(512, 21128), dtype=float32, numpy=
 array([[ 0.2335467 , -0.6062009 ,  0.37243122, ..., -0.02789687,
          1.1900101 , -0.04584426],
        [ 0.2335467 , -0.6062009 ,  0.37243122, ..., -0.02789687,
          1.1900101 , -0.04584426],
        [ 0.2335467 , -0.6062009 ,  0.37243122, ..., -0.02789687,
          1.1900101 , -0.04584426],
        ...,
        [ 0.2335467 , -0.6062009 ,  0.37243122, ..., -0.02789687,
          1.1900101 , -0.04584426],
        [ 0.2335467 , -0.6062009 ,  0.37243122, ..., -0.02789687,
          1.1900101 , -0.04584426],
        [ 0.2335467 , -0.6062009 ,  0.37243122, ..., -0.02789687,
          1.1900101 , -0.04584426]], dtype=float32)>,
 <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-0.05420166, -0.00963133]], dtype=float32)>,
 <tf.Tensor: shape=(1, 768), dtype=float32, numpy=
 array([[-5.32185376e-01, -5.94466746e-01, -4.74589109e-01,
          5.17674029e-01,  1.22628480e-01, -7.56749511e-01,
          1.34524375e-01,  1.2

In [11]:
archive_file = "D:/code/py_nlp_classify/model/bert/google-bert-base-zh/bert_model.ckpt"

In [12]:
bert_model._init_from_pretrained_model(archive_file)

INFO:tensorflow:从文件中还原预训练模型
INFO:tensorflow:tvars: [<tf.Variable 'bert_pre_trained_model/bert/embeddings/word_embeddings:0' shape=(21128, 768) dtype=float32, numpy=
array([[-0.00986778, -0.03012765,  0.0104761 , ..., -0.03034461,
        -0.02464302,  0.03073202],
       [ 0.00797483, -0.02573283, -0.00657339, ...,  0.00385186,
        -0.01467727, -0.00928151],
       [-0.009119  , -0.0116833 , -0.02754286, ..., -0.02966523,
        -0.00798262, -0.03110151],
       ...,
       [ 0.00085306, -0.00071852,  0.03585234, ...,  0.00338991,
         0.00717245, -0.00760912],
       [-0.00406476, -0.00418313, -0.02780975, ..., -0.012734  ,
        -0.01159898, -0.01964439],
       [-0.00443669,  0.00640044,  0.0063586 , ...,  0.01330292,
        -0.02011607,  0.02084378]], dtype=float32)>, <tf.Variable 'bert_pre_trained_model/bert/embeddings/position_embeddings:0' shape=(512, 768) dtype=float32, numpy=
array([[ 1.8744480e-02,  1.4665171e-02,  1.8223317e-02, ...,
         3.1692376e-05, -1.47

In [26]:
bert_model(bert_model.dummy_inputs(512), mode="eval", output_features=False)

input_shape [1, 512]


(<tf.Tensor: shape=(512, 21128), dtype=float32, numpy=
 array([[2.2154024, 2.57977  , 2.4387329, ..., 0.747318 , 3.8504128,
         2.393185 ],
        [2.2154024, 2.57977  , 2.4387329, ..., 0.747318 , 3.8504128,
         2.393185 ],
        [2.2154024, 2.57977  , 2.4387329, ..., 0.747318 , 3.8504128,
         2.393185 ],
        ...,
        [2.2154024, 2.57977  , 2.4387329, ..., 0.747318 , 3.8504128,
         2.393185 ],
        [2.2154024, 2.57977  , 2.4387329, ..., 0.747318 , 3.8504128,
         2.393185 ],
        [2.2154024, 2.57977  , 2.4387329, ..., 0.747318 , 3.8504128,
         2.393185 ]], dtype=float32)>,
 <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-0.2736026 ,  0.99370974]], dtype=float32)>,
 <tf.Tensor: shape=(1, 768), dtype=float32, numpy=
 array([[-0.72479117, -0.6492197 , -0.6313156 ,  0.7920847 ,  0.33676788,
          0.33827484,  0.02391161,  0.9911232 ,  0.77682114,  0.42134544,
          0.7303043 , -0.94188184,  0.3583821 ,  0.22749901,  0.62287325,


In [14]:
# import importlib
# from easytransfer.model_zoo import modeling_utils, modeling_bert
# importlib.reload(modeling_utils)
# importlib.reload(modeling_bert)
# from easytransfer.model_zoo.modeling_bert import BertConfig, BertPreTrainedModel, MyBertPreTrainedModel
# from easytransfer.model_zoo.modeling_utils import PretrainedConfig

# bert_config = BertConfig.get(bert_config_path)
# my_bert_model = MyBertPreTrainedModel(bert_config)

In [15]:
my_bert_model._init_from_pretrained_model(archive_file)

从文件中还原预训练模型
network_name_to_variable ['my_bert_pre_trained_model/bert/embeddings/word_embeddings', 'my_bert_pre_trained_model/bert/embeddings/position_embeddings', 'my_bert_pre_trained_model/bert/embeddings/token_type_embeddings', 'my_bert_pre_trained_model/bert/embeddings/LayerNorm/gamma', 'my_bert_pre_trained_model/bert/embeddings/LayerNorm/beta', 'my_bert_pre_trained_model/bert/pooler/dense/kernel', 'my_bert_pre_trained_model/bert/pooler/dense/bias', 'my_bert_pre_trained_model/cls/predictions/output_bias', 'my_bert_pre_trained_model/cls/predictions/transform/dense/kernel', 'my_bert_pre_trained_model/cls/predictions/transform/dense/bias', 'my_bert_pre_trained_model/cls/seq_relationship/output_weights', 'my_bert_pre_trained_model/cls/seq_relationship/output_bias']
Variable: bert/encoder/layer_0/output/dense/kernel in ckpt not in trainable variable
Variable: bert/encoder/layer_0/intermediate/dense/kernel in ckpt not in trainable variable
Variable: bert/encoder/layer_9/attention/self/ke

In [16]:
my_bert_model(my_bert_model.dummy_inputs(512), mode="eval", output_features=False)

input_shape [1, 512]


(<tf.Tensor: shape=(512, 21128), dtype=float32, numpy=
 array([[ 0.49204844,  0.48211277,  0.4653633 , ..., -3.3483171 ,
         -1.4075947 , -1.322042  ],
        [ 0.49204844,  0.48211277,  0.4653633 , ..., -3.3483171 ,
         -1.4075947 , -1.322042  ],
        [ 0.49204844,  0.48211277,  0.4653633 , ..., -3.3483171 ,
         -1.4075947 , -1.322042  ],
        ...,
        [ 0.49204844,  0.48211277,  0.4653633 , ..., -3.3483171 ,
         -1.4075947 , -1.322042  ],
        [ 0.49204844,  0.48211277,  0.4653633 , ..., -3.3483171 ,
         -1.4075947 , -1.322042  ],
        [ 0.49204844,  0.48211277,  0.4653633 , ..., -3.3483171 ,
         -1.4075947 , -1.322042  ]], dtype=float32)>,
 <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-0.10657424,  1.0788873 ]], dtype=float32)>,
 <tf.Tensor: shape=(1, 768), dtype=float32, numpy=
 array([[-0.644912  , -0.8142637 , -0.7562132 ,  0.8439509 , -0.4156421 ,
          0.71163225,  0.5849316 ,  0.99201447,  0.648055  , -0.12371132,
  

In [37]:
for x, y in zip(bert_model.weights, my_bert_model.weights):
    print(tf.equal(x, y).numpy().all())

True
True
True
True
True
True
True
True
True
True
True
True


In [30]:
print(bert_model.weights[0])
print(my_bert_model.weights[0])

<tf.Variable 'bert_pre_trained_model/bert/embeddings/word_embeddings:0' shape=(21128, 768) dtype=float32, numpy=
array([[ 0.02615827,  0.01094903, -0.01868878, ...,  0.09030139,
         0.0028486 ,  0.00642775],
       [ 0.00211436,  0.02164099,  0.00108996, ...,  0.08090564,
         0.00178312,  0.02494784],
       [ 0.01467745,  0.00050856,  0.00283794, ...,  0.08360939,
         0.01208044,  0.02821462],
       ...,
       [ 0.03456404,  0.00210567,  0.00852101, ...,  0.00853979,
         0.03371229,  0.00985317],
       [ 0.05406349,  0.02890619,  0.02626012, ...,  0.0525924 ,
         0.06508742,  0.03532186],
       [ 0.02002425,  0.00229523, -0.00892451, ...,  0.07987329,
        -0.05615233,  0.02471835]], dtype=float32)>
<tf.Variable 'my_bert_pre_trained_model/bert/embeddings/word_embeddings:0' shape=(21128, 768) dtype=float32, numpy=
array([[ 0.02615827,  0.01094903, -0.01868878, ...,  0.09030139,
         0.0028486 ,  0.00642775],
       [ 0.00211436,  0.02164099,  0.00108

In [17]:
[v.name for v in bert_model.weights]

['bert_pre_trained_model/bert/embeddings/word_embeddings:0',
 'bert_pre_trained_model/bert/embeddings/position_embeddings:0',
 'bert_pre_trained_model/bert/embeddings/token_type_embeddings:0',
 'bert_pre_trained_model/bert/embeddings/LayerNorm/gamma:0',
 'bert_pre_trained_model/bert/embeddings/LayerNorm/beta:0',
 'bert_pre_trained_model/bert/pooler/dense/kernel:0',
 'bert_pre_trained_model/bert/pooler/dense/bias:0',
 'bert_pre_trained_model/cls/predictions/output_bias:0',
 'bert_pre_trained_model/cls/predictions/transform/dense/kernel:0',
 'bert_pre_trained_model/cls/predictions/transform/dense/bias:0',
 'bert_pre_trained_model/cls/seq_relationship/output_weights:0',
 'bert_pre_trained_model/cls/seq_relationship/output_bias:0']

In [18]:
[v.name for v in my_bert_model.weights]

['my_bert_pre_trained_model/bert/embeddings/word_embeddings:0',
 'my_bert_pre_trained_model/bert/embeddings/position_embeddings:0',
 'my_bert_pre_trained_model/bert/embeddings/token_type_embeddings:0',
 'my_bert_pre_trained_model/bert/embeddings/LayerNorm/gamma:0',
 'my_bert_pre_trained_model/bert/embeddings/LayerNorm/beta:0',
 'my_bert_pre_trained_model/bert/pooler/dense/kernel:0',
 'my_bert_pre_trained_model/bert/pooler/dense/bias:0',
 'my_bert_pre_trained_model/cls/predictions/output_bias:0',
 'my_bert_pre_trained_model/cls/predictions/transform/dense/kernel:0',
 'my_bert_pre_trained_model/cls/predictions/transform/dense/bias:0',
 'my_bert_pre_trained_model/cls/seq_relationship/output_weights:0',
 'my_bert_pre_trained_model/cls/seq_relationship/output_bias:0']

In [19]:
[v.name for v in my_bert_model.bert.weights]

['my_bert_pre_trained_model/bert/embeddings/word_embeddings:0',
 'my_bert_pre_trained_model/bert/embeddings/position_embeddings:0',
 'my_bert_pre_trained_model/bert/embeddings/token_type_embeddings:0',
 'my_bert_pre_trained_model/bert/embeddings/LayerNorm/gamma:0',
 'my_bert_pre_trained_model/bert/embeddings/LayerNorm/beta:0',
 'my_bert_pre_trained_model/bert/pooler/dense/kernel:0',
 'my_bert_pre_trained_model/bert/pooler/dense/bias:0']

In [20]:
[v.name for v in my_bert_model.bert.embeddings.weights]

['my_bert_pre_trained_model/bert/embeddings/word_embeddings:0',
 'my_bert_pre_trained_model/bert/embeddings/position_embeddings:0',
 'my_bert_pre_trained_model/bert/embeddings/token_type_embeddings:0',
 'my_bert_pre_trained_model/bert/embeddings/LayerNorm/gamma:0',
 'my_bert_pre_trained_model/bert/embeddings/LayerNorm/beta:0']

In [21]:
[v.name for v in my_bert_model.mlm.weights]

['my_bert_pre_trained_model/cls/predictions/output_bias:0',
 'my_bert_pre_trained_model/cls/predictions/transform/dense/kernel:0',
 'my_bert_pre_trained_model/cls/predictions/transform/dense/bias:0',
 'my_bert_pre_trained_model/bert/embeddings/word_embeddings:0',
 'my_bert_pre_trained_model/bert/embeddings/position_embeddings:0',
 'my_bert_pre_trained_model/bert/embeddings/token_type_embeddings:0',
 'my_bert_pre_trained_model/bert/embeddings/LayerNorm/gamma:0',
 'my_bert_pre_trained_model/bert/embeddings/LayerNorm/beta:0']

In [22]:
[v.name for v in my_bert_model.nsp.weights]

['my_bert_pre_trained_model/cls/seq_relationship/output_weights:0',
 'my_bert_pre_trained_model/cls/seq_relationship/output_bias:0']

In [23]:
tf.train.list_variables('D:/code/py_nlp_classify/model/bert/google-bert-base-zh/bert_model.ckpt')

[('bert/embeddings/LayerNorm/beta', [768]),
 ('bert/embeddings/LayerNorm/gamma', [768]),
 ('bert/embeddings/position_embeddings', [512, 768]),
 ('bert/embeddings/token_type_embeddings', [2, 768]),
 ('bert/embeddings/word_embeddings', [21128, 768]),
 ('bert/encoder/layer_0/attention/output/LayerNorm/beta', [768]),
 ('bert/encoder/layer_0/attention/output/LayerNorm/gamma', [768]),
 ('bert/encoder/layer_0/attention/output/dense/bias', [768]),
 ('bert/encoder/layer_0/attention/output/dense/kernel', [768, 768]),
 ('bert/encoder/layer_0/attention/self/key/bias', [768]),
 ('bert/encoder/layer_0/attention/self/key/kernel', [768, 768]),
 ('bert/encoder/layer_0/attention/self/query/bias', [768]),
 ('bert/encoder/layer_0/attention/self/query/kernel', [768, 768]),
 ('bert/encoder/layer_0/attention/self/value/bias', [768]),
 ('bert/encoder/layer_0/attention/self/value/kernel', [768, 768]),
 ('bert/encoder/layer_0/intermediate/dense/bias', [3072]),
 ('bert/encoder/layer_0/intermediate/dense/kernel',

In [24]:
reader = tf.train.load_checkpoint("D:/code/py_nlp_classify/model/bert/google-bert-base-zh/bert_model.ckpt")
var_to_shape_map = reader.get_variable_to_shape_map()

In [25]:
list(var_to_shape_map.keys())

['bert/encoder/layer_0/output/dense/kernel',
 'bert/encoder/layer_0/intermediate/dense/kernel',
 'bert/embeddings/LayerNorm/beta',
 'bert/encoder/layer_9/attention/self/key/bias',
 'bert/encoder/layer_11/attention/output/dense/kernel',
 'bert/embeddings/LayerNorm/gamma',
 'bert/embeddings/position_embeddings',
 'bert/encoder/layer_5/intermediate/dense/bias',
 'bert/encoder/layer_2/attention/output/LayerNorm/gamma',
 'bert/encoder/layer_11/attention/self/query/bias',
 'bert/encoder/layer_1/attention/self/key/kernel',
 'bert/encoder/layer_5/output/dense/bias',
 'bert/embeddings/token_type_embeddings',
 'bert/encoder/layer_10/intermediate/dense/kernel',
 'bert/embeddings/word_embeddings',
 'bert/encoder/layer_0/attention/output/LayerNorm/beta',
 'bert/encoder/layer_0/attention/output/dense/kernel',
 'bert/encoder/layer_0/attention/output/dense/bias',
 'bert/encoder/layer_0/attention/output/LayerNorm/gamma',
 'bert/encoder/layer_0/attention/self/key/bias',
 'bert/encoder/layer_0/attention/